### ISSUE TITLE
Error: cannot load such file -- hbc

### ISSUE THREAD

**Issue by y0y0z** [buo/homebrew-cask-upgrade#111] opened 2018-09-04 15:47 UTC
when i execute `brew cu -y -a` i get an error
```bash
Error: cannot load such file -- hbc
```

# reproduce
```bash
$ cd "$(brew --repo)
$ git fetch
$ git reset --hard origin/master
HEAD is now at 817b72d5b Merge pull request #4807 from MikeMcQuaid/cask-move
$ brew update
Already up-to-date.

$ brew cu -y -a
Error: cannot load such file -- hbc
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:4:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

i saw https://github.com/buo/homebrew-cask-upgrade/issues/12 but it is not really helpful.

can someone please confirm the issue?
shall i file a bug?

**Comment by alistairharris** [comment] 2018-09-04 23:17
I've also begun experiencing this very same issue.

**Comment by yangyaofei** [comment] 2018-09-05 06:29
same issue ...

**Comment by boboldehampsink** [comment] 2018-09-05 06:40
Same here

**Comment by ondrejfuhrer** [comment] 2018-09-05 08:12
This is a duplicate of #109 and is fixed in #110 . Hope it will get merged soon. Meanwhile you can you the branch from the MR to have it working

**Comment by wesker0918** [comment] 2018-09-05 10:03
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb 
`require "bcu/options"
require "hbc"
require "extend/formatter"
require "extend/hbc"`
change to 
`require "bcu/options"
#require "hbc"
require "extend/formatter"
require "extend/hbc"`

**Closed** 2018-09-05 15:15 UTC

**Comment by y0y0z** [comment] 2018-09-06 11:30
@buo: the issue rose again
```bash
$ cd "$(brew --repo)"
$ git fetch
$ git reset --hard origin/master
HEAD is now at 3d992dbef Merge pull request #4839 from Homebrew/revert-4831-homebrew-arch
$ brew update
Already up-to-date.
$ brew cu -y -a
Error: uninitialized constant Hbc
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:6:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```
