### ISSUE TITLE
Not work for ghidra

### ISSUE THREAD

**Issue by littleneko** [buo/homebrew-cask-upgrade#204] opened 2022-05-07 03:47 UTC
I use `brew cu -a` to upgrade all my cask apps, but it not work with `ghidra`:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/6368915/167236864-c8e38c7b-3585-4b84-b2bb-8be24be6e5dc.png">

if i enter 'Y' and after upgraded, the ghidra app is disappeared. All files in `/usr/local/Caskroom/ghidra` are disappeared.

**Comment by ondrejfuhrer** [comment] 2022-05-09 07:55
Hey @littleneko , have you checked any error messages after the installation? This is most probably not an issue with this tool but with `brew` itself (or the cask). 

If you run `brew reinstall --cask ghidra` manually, do you get any errors?

**Comment by littleneko** [comment] 2022-05-12 02:56
> Hey @littleneko , have you checked any error messages after the installation? This is most probably not an issue with this tool but with `brew` itself (or the cask).
> 
> If you run `brew reinstall --cask ghidra` manually, do you get any errors?

Hey @ondrejfuhrer I run `brew install --cask ghidra`, it show me "Warning: Cask 'ghidra' is already installed.".

But, if i run `brew reinstall --cask ghidra`, i got the error:
```
==> Uninstalling Cask ghidra
Error: No such file or directory @ rb_file_s_rename - (/usr/local/Caskroom/ghidra/10.1.3-20220421, /usr/local/Caskroom/ghidra/10.1.3,20220421)
```

**Comment by ondrejfuhrer** [comment] 2022-05-18 18:16
I guess there was something wrong going when installing the update. I would suggest following steps

1. Try to uninstall (`brew uninstall ghidra`) - might fail
2. Cleanup any residue by deleting the caskroom folder `rm -fr /usr/local/Caskroom/ghidra` )
3. install the app again `brew install --cask ghidra` 

It seems that there were something weird going on with the version itself which broke your caskroom. the above might help 🙂

**Comment by ondrejfuhrer** [comment] 2022-07-09 21:39
Assuming the above suggestions worked and therefore I'm closing this issue. If there is any followup, feel free to reopen it.

**Closed by ondrejfuhrer** 2022-07-09 21:39 UTC
Labels: :bug: bug

**Comment by arnaugamez** [comment] 2024-11-30 09:52
I was going to open an issue for this and found this old one. The issue is still present on ghidra. Same behavior as the original issue message. The only way to solve it is to manually delete the `Caskroom/ghidra` folder (which is already empty after the `brew cu` and force install again. Any idea why this happens only for ghidra?

**Comment by ondrejfuhrer** [comment] 2025-01-06 12:45
@arnaugamez Frankly, no idea. But since `cu` uses the "standard" `brew` commands to operate, it shouldn't cause it by itself.
