### ISSUE TITLE
brew cu broken

### ISSUE THREAD

**Issue by Fischmuetze** [buo/homebrew-cask-upgrade#117] opened 2018-09-07 07:54 UTC
I got since days this message by using any brew cu command

$brew cu -facy
Error: cannot load such file -- cask/all
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:4:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

**Comment by ondrejfuhrer** [comment] 2018-09-07 07:56
Hey @Fischmuetze I would suggest running `brew update` before, that should fix this issue. You will the probably still get the one described at #112 but that will be fixed when the PR is merged.

**Comment by Fischmuetze** [comment] 2018-09-07 08:00
Thanks but It's clear of course and doesn't work

$ brew update && brew cu
Already up-to-date.
Error: uninitialized constant Hbc
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:6:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

Also I tried to fix it with
https://github.com/buo/homebrew-cask-upgrade/issues/112#issuecomment-418793946
but it wasn't a solution

**Comment by warb2n** [comment] 2018-09-07 19:46
sama, problem =@

**Comment by y0y0z** [comment] 2018-09-08 06:16
probably duplicate of https://github.com/buo/homebrew-cask-upgrade/issues/112 and https://github.com/buo/homebrew-cask-upgrade/issues/113

**Comment by symgryph** [comment] 2018-09-09 03:34
same problem sadness.

**Comment by softmentor** [comment] 2018-09-09 14:51
same issue, any work-arounds

**Comment by fedya** [comment] 2018-09-09 15:11
same

**Comment by jerson** [comment] 2018-09-09 23:40
same

**Comment by yelban** [comment] 2018-09-10 00:17
same

**Comment by whalesingswee** [comment] 2018-09-10 02:15
same issue here as well

**Comment by giacgbj** [comment] 2018-09-10 06:04
Four "same" e-mails this morning (in my timezone, at least)! 

Do you know every time someone writes a comment a notification (e-mail) is sent to all the people who have the notifications enabled? Not only the followers of this issue, but also the one who "Watch"ed the repository.
Please, use the reactions if your comment doesn't add anything to the discussion.

**Comment by twreid** [comment] 2018-09-10 13:44
I am also having this issue and brew update doesn't help

brew update && brew cu
Already up-to-date.
Error: cannot load such file -- cask/all
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:4:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

**Comment by ondrejfuhrer** [comment] 2018-09-10 13:56
@twreid 
https://github.com/buo/homebrew-cask-upgrade/pull/114#issuecomment-419876505

**Closed** 2018-09-13 13:56 UTC
