### ISSUE TITLE
Error: uninitialized constant Hbc

### ISSUE THREAD

**Issue by rjcoelho** [buo/homebrew-cask-upgrade#113] opened 2018-09-06 08:41 UTC
brew cu

`
Error: uninitialized constant Hbc
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:3:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:6:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
`

brew cask doctor
`
==> Homebrew Version
1.7.3-57-g132aa14
==> macOS
10.13.2
==> SIP
Enabled
==> Java
10.0.2, 10.0.1, 10, 9.0.4, 9.0.1, 9, 1.8.0_144, 1.8.0_141, 1.8.0_131, 1.8.0_121, 1.8.0_112, 1.8.0_92, 1.8.0_77, 1.8.0_74, 1.8.0_45
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4046 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (195 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1175 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (151 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
`

**Comment by imyelmo** [comment] 2018-09-06 09:07
I'm having exactly the same problem

**Comment by ondrejfuhrer** [comment] 2018-09-06 09:18
Most probably caused by https://github.com/Homebrew/brew/pull/4838 

I'll take a look on that

**Comment by y0y0z** [comment] 2018-09-06 11:31
[i've update an issue which was closed yesterday](https://github.com/buo/homebrew-cask-upgrade/issues/111#issuecomment-419060505).

**Comment by y0y0z** [comment] 2018-09-06 15:36
probably duplicate of https://github.com/buo/homebrew-cask-upgrade/issues/112

**Comment by LeerGo** [comment] 2018-09-07 05:06
same as me

**Comment by matteodisabatino** [comment] 2018-09-07 08:59
Same as me

**Comment by opengit** [comment] 2018-09-07 23:55
Same as me

**Comment by jzhzj** [comment] 2018-09-08 00:41
Same as me

**Comment by gbanyan** [comment] 2018-09-08 02:13
Same as me

**Comment by alistairharris** [comment] 2018-09-09 16:33
Same problem.

**Comment by vecernik** [comment] 2018-09-10 07:48
Error: uninitialized constant Hbc
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:3:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:6:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

**Comment by bzerangue** [comment] 2018-09-11 14:59
same as me. macOS 10.13.6.

**Comment by AJCrowley** [comment] 2018-09-11 20:30
Same here. I had a problem a few weeks ago that looked kind of similar, but wasn't exactly the same. I was able to resolve it by untapping and retapping buo/cask-upgrade. That doesn't seem to have worked this time.

**Comment by tarikkavaz** [comment] 2018-09-11 21:38
Thanks! 
```ruby
Hbc = Cask
```
worked for me.

**Comment by timbotetsu** [comment] 2018-09-12 07:47
> Same here. I had a problem a few weeks ago that looked kind of similar, but wasn't exactly the same. I was able to resolve it by untapping and retapping buo/cask-upgrade. That doesn't seem to have worked this time.
> 
> Easy fix though (thanks to @ondrejfuhrer for clarifying what was causing the issue) - open up the file `/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb`
> 
> At the start of the file (before CASKROOM = Hbc.methods), add the following line of code:
> 
> ```ruby
> Hbc = Cask
> ```
> 
> That's it, should work for you again until a proper fix emerges.

this works

**Comment by rjcoelho** [comment] 2018-09-12 08:29
https://github.com/buo/homebrew-cask-upgrade/pull/114 worked for me

**Closed** 2018-09-13 13:56 UTC
