### ISSUE TITLE
error on brew cu

### ISSUE THREAD

**Issue by hmstanley** [buo/homebrew-cask-upgrade#112] opened 2018-09-05 15:58 UTC
Error: cannot load such file -- cask/all
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:4:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

 ~ ▶ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.7.3
Homebrew/homebrew-cask (git revision 02f179; last commit 2018-09-05)
==> macOS
10.13.6
==> SIP
Enabled
==> Java
N/A
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (4045 casks)
==> Contents of $LOAD_PATH
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"

**Comment by greveritt** [comment] 2018-09-05 16:06
Hmm, it looks like this is caused by #110 ?

**Comment by hmstanley** [comment] 2018-09-05 16:07
Do i need to do anything? to fix?

**Comment by y0y0z** [comment] 2018-09-05 16:26
@hmstanley: do this
```bash
$ cd "$(brew --repo)
$ git fetch
$ git reset --hard origin/master
$ brew update
```

**Comment by hmstanley** [comment] 2018-09-05 17:14
That worked.  Please close.

**Comment by mrichman** [comment] 2018-09-05 18:07
@hmstanley Why close this issue? You are not the only one affected, and there needs to be a better fix than nuking the git repo.

**Comment by hmstanley** [comment] 2018-09-05 18:08
Oh, fair enough.. sorry.. was just pointing out that it fixed it for me.

**Comment by mrichman** [comment] 2018-09-05 18:10
@hmstanley That's cool.

Also, the first line in the proposed workaround is incorrect. You need to omit the double quotes (`"`).

The correct command is `cd $(brew --repo)`

**Comment by hmstanley** [comment] 2018-09-05 18:11
yea. Fixed that myself.. but yes.

**Comment by AJCrowley** [comment] 2018-09-05 19:01
Just came here because of this. Thanks for the fix!

**Comment by QuattroGam3r** [comment] 2018-09-05 19:13
Thank you for the quick fix!

**Comment by voody77** [comment] 2018-09-05 20:27
Thx, fixed!

**Comment by Hanstad** [comment] 2018-09-06 06:08
Thanks!

**Comment by pl0pix** [comment] 2018-09-06 07:54
Thanks!

**Comment by giacgbj** [comment] 2018-09-06 08:34
I followed the workaround, but now the error is:
```
ijhack:Homebrew jhack$ brew cu -ay
Error: uninitialized constant Hbc
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:3:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:6:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

```

**Comment by untcha** [comment] 2018-09-06 09:16
Same here. Workaround leads into: Error: uninitialized constant Hbc

**Comment by ondrejfuhrer** [comment] 2018-09-06 09:26
Yeah, there was another rename happening, there is already a fix for that waiting in PR https://github.com/buo/homebrew-cask-upgrade/pull/114 

Just waiting for @buo to merge that.
Meanwhile feel free to use my branch from that PR

**Comment by Fischmuetze** [comment] 2018-09-07 08:05
@ondrejfuhrer 
> Meanwhile feel free to use my branch from that PR

How?

**Comment by ondrejfuhrer** [comment] 2018-09-07 08:28
@Fischmuetze If you don't know, would be better if you wait until the master branch gets updated. It involves some knowledge about git and be able to fix potential issues. Therefore I would strongly recommend right now for you to wait 🙂

**Comment by Fischmuetze** [comment] 2018-09-07 08:30
Thanks a lot ... hopefully the fix it will be available soon

**Comment by y0y0z** [comment] 2018-09-10 21:05
@ondrejfuhrer: any idea what keeps it from being merged if it fixes the issue?

**Comment by greveritt** [comment] 2018-09-10 21:12
@y0y0z I'm guessing that @buo simply hasn't had the time to review it yet; he approved another PR that @ondrejfuhrer created for this general issue.

**Comment by y0y0z** [comment] 2018-09-12 14:39
@buo: we all love you, could you please help us out with the merge? :) :shipit:

**Closed** 2018-09-13 13:56 UTC
