### ISSUE TITLE
Error: No such file or directory @ rb_sysopen - /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/addressable-2.8.0/data/unicode.data

### ISSUE THREAD

**Issue by tiancheng92** [buo/homebrew-cask-upgrade#205] opened 2022-05-18 00:12 UTC
```bash
# input
brew cu

# output
Error: No such file or directory @ rb_sysopen - /opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/addressable-2.8.0/data/unicode.data
```

```bash
# input
brew doctor

# output
Your system is ready to brew.
```

```bash
# input
brew config

# output
HOMEBREW_VERSION: 3.4.11-53-g34dd8e3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 34dd8e305789a5433d345a29b03a4d4f3a568d1e
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0f98d77858de1aa1738d1d09ad4d226114255cbe
Core tap last commit: 65 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_BAT: set
HOMEBREW_CASK_OPTS: []
HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: 1
HOMEBREW_CLEANUP_MAX_AGE_DAYS: 1
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_FORCE_BREWED_CURL: set
HOMEBREW_FORCE_BREWED_GIT: set
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_ANALYTICS: set
HOMEBREW_NO_AUTO_UPDATE: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 13.1.6 build 1316
Git: 2.36.1 => /opt/homebrew/opt/git/bin/git
Curl: 7.83.1 => /opt/homebrew/opt/curl/bin/curl
macOS: 12.4-arm64
CLT: 13.4.0.0.1.1651278267
Xcode: N/A
Rosetta 2: false
```

**Comment by mikelorant** [comment] 2022-05-18 01:34
Issue looks to be caused by this commit.

https://github.com/Homebrew/brew/commit/fb8a4e565836e33f2195ff49eaf10535d8bb78a0

**Comment by mikelorant** [comment] 2022-05-18 01:41
My fix so far has been this:
```
cp -R /usr/local/lib/ruby/gems/2.6.0/gems/addressable-2.8.0/data /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/addressable-2.8.0
```

**Comment by liukaiwen0422** [comment] 2022-05-18 02:12
I don't have dir /usr/local/lib/ruby/gems/2.6.0
I have dir /usr/local/lib/ruby/gems/3.10
how to fix this error,plz?

**Comment by mikelorant** [comment] 2022-05-18 02:24
Likely just replace the `2.6.0` with `3.10`.

**Comment by liukaiwen0422** [comment] 2022-05-18 02:38
> Likely just replace the `2.6.0` with `3.10`.
> 
> 

But there is no folder with path like 2.6

**Comment by mikelorant** [comment] 2022-05-18 02:46
Otherwise just get the `unicode.data` file from here:

https://github.com/sporkmonger/addressable/tree/main/data

It is only this file that needs to be in that directory.

**Comment by liukaiwen0422** [comment] 2022-05-18 05:09
yes! it's work,thanks

> Otherwise just get the `unicode.data` file from here:
> 
> https://github.com/sporkmonger/addressable/tree/main/data
> 
> It is only this file that needs to be in that directory.

**Comment by ondrejfuhrer** [comment] 2022-05-18 08:16
@tiancheng92 did this work for you as well? Can we close this then?

**Comment by mikelorant** [comment] 2022-05-18 08:23
I think this is an issue that will impact others. This may require an update to this addon.

**Comment by foolioo** [comment] 2022-05-18 09:10
i had the same issue and resolved it by
```shell
mkdir /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/addressable-2.8.0/data/
wget https://raw.githubusercontent.com/sporkmonger/addressable/main/data/unicode.data -O /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/addressable-2.8.0/data/unicode.data
```

**Comment by ondrejfuhrer** [comment] 2022-05-18 13:35
@z0rc I don't think there is an easy way. Does it happen immediately or you already get some output before it errors out?

**Comment by z0rc** [comment] 2022-05-18 13:39
@ondrejfuhrer Almost immediately after exec, no additional output.
```
% brew cu
Error: No such file or directory @ rb_sysopen - /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/addressable-2.8.0/data/unicode.data
```

Tested also `brew cu --verbose --no-brew-update`, but additional options didn't have effect, error remains as it. `brew cu --help` works okay though.

**Comment by dbeenlee** [comment] 2022-05-18 16:52
> yes! it's work,thanks
> 
> >

yes! it's work,thanks

**Comment by ondrejfuhrer** [comment] 2022-05-18 17:37
@z0rc & @kovalchik can you try running `brew vendor-install ruby` if that fixes it maybe? 
Since there is no input then it means something is off with the initialisation of this extension, but I can't find anything even closely related to the issue described.

**Comment by ondrejfuhrer** [comment] 2022-05-18 18:03
Didn't meant to close it immediately. @kovalchik can you try `brew update` and then `brew cu` if it works now? I managed to reproduce the issue and might have found the culprit. Not sure though if it didn't break anything else 😆  🤞

**Comment by kovalchik** [comment] 2022-05-18 18:37
@ondrejfuhrer That worked! After running `brew update`, `brew cu` ran and completed successfully. 🙌

**Comment by z0rc** [comment] 2022-05-18 18:47
I also confirm that this fixed the issue. Thanks!

**Comment by samford** [comment] 2022-05-18 18:48
From a quick glance, this issue is likely due to needing to run `#install_bundler_gems` at some point. We usually call `Homebrew.install_bundler_gems!` in commands that use parts of brew that involve external gems (like `addressable`) but I forgot to handle that in the aforementioned PR. I imagine it's affecting your code because `cask/audit` requires `livecheck/livecheck` which now requires `addressable`.

Anyone who's seeing this error has already run a dev-cmd before (i.e., my commit isn't in a `brew` release yet), so they should be able to safely resolve the error by running `brew install-bundler-gems`.

I'm working on a follow-up PR on our end but, unfortunately, I have to create a separate PR beforehand to modify the behavior of `#install_bundler_gems` (to be able to safely call it in livecheck). Once that's done and I've added `Homebrew.install_bundler_gems!` in related parts of `brew` (`livecheck`, `bump`, `cask/audit`), it may resolve this issue for you.

If you want to resolve this quickly or err on the safe side, you can add a `Homebrew.install_bundler_gems!` call in your code (somewhere early on, where you're setting things up). If you search the `brew` codebase for `install_bundler_gems!`, you'll find some example usage.

**Comment by ondrejfuhrer** [comment] 2022-05-18 19:24
I'll consider this issue being resolved then 🙂  thank you all for your help investigating this.

**Closed by ondrejfuhrer** 2022-05-18 19:24 UTC
Labels: :bug: bug

**Comment by samford** [comment] 2022-05-18 21:19
After investigating further, we just needed to vendor more of `addressable`. We were already vendoring the `lib` directory by default but we also need the `data` directory, where `unicode.data` is found. I didn't see the error when I was testing because my `addressable` directory had all the files from when it was installed. We temporarily reverted the aforementioned commit but a fix will be included when it's reinstated, so this shouldn't require changes on your end.

At this point, users can resolve the error by running `brew update`. This will work now (with the commit reverted) as well as after the commit is reinstated with an accompanying fix.
